### ISSUE TITLE
Use of "browsing data" permission

### ISSUE THREAD

**Issue by mubaidr** [ForgetThatPage/ForgetThatPage#5]
I see you are using content script to clear session and local storage, while chrome has an awesome api to manage/clear all browsing Data including all types of storages. 

Use of "browsingData" permission [https://developer.chrome.com/extensions/browsingData](url) will greatly simplify the UI and back-end of the extension and might be more reliable and efficient too.

**Comment by cyril-we** [comment]
I will have a look at that, thanks a lot

**Comment by cyril-we** [comment]
"Your code should provide a timestamp which indicates the historical date after which the user's browsing data should be removed."

I think I looked at this because it

**Comment by mubaidr** [comment]
It is possible to use 0 to remove since start. But i have found another cause of avoiding this, For now, chrome.browsingData.remove cannot be limited to a single url/domain, which is totaly not acceptable in our use. 

info: [https://bugs.chromium.org/p/chromium/issues/detail?id=113194](url)

**Comment by cyril-we** [comment]
Ok, thanks anyway for your involvement ;-)
