### ISSUE TITLE
Add option to delete all pages for site

### ISSUE THREAD

**Issue by Gitoffthelawn** [ForgetThatPage/ForgetThatPage#8]
Add an option to delete all pages for the current domain.

For example, if on:
`www.example.com/page1`
then go to:
`abc.example.com/page2`
then invoke ForgetThatPage delete, everything from:
`example.com`

**Comment by cyril-we** [comment]
I'll do it, but it will be disabled by default.

**Comment by Gitoffthelawn** [comment]
Sounds good, thanks!

**Comment by cyril-we** [comment]
Thanks to you

**Comment by TUrabbIT** [comment]
I want to support this issue.
I have committed one first step in this direction.

**Comment by cyril-we** [comment]
Thanks, I'd need to include your code and make it optional

**Comment by cyril-we** [comment]
Quick update on this issue, I'm working on it thanks to @TUrabbIT pull request. Will be included soon.

**Comment by Qwash** [comment]
Any progess on this?

**Comment by cyril-we** [comment]
I'm a bit lazy on the project but it's on progress

**Comment by cyril-we** [comment]
fixed in v1.6.0

**Comment by Gitoffthelawn** [comment]
Thanks!
